### ISSUE TITLE
本书132页,也就是5.1.2 In[69]在python3.6和3.7下报错

### ISSUE THREAD

**Issue by CheungChan** [BrambleXu/pydata-notebook#25]
```python
>>> import pandas as pd
>>> import numpy as np
>>> pop={'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
>>> pd.DataFrame(pop,index=[2001,2002,2003])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 459, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 7359, in _arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 7661, in _homogenize
    oindex = index.astype('O')
AttributeError: 'list' object has no attribute 'astype'```

报错如上, 最新版的pandas 0.23.4 python3.6和3.7下都报错

**Comment by BigOrange128** [comment]
我也有这个问题。

**Comment by BrambleXu** [comment]
我在pandas0.22, python3.6下使用没有问题。这个应该是pandas新版本带来的问题，试一试下面的代码。
```
pd.DataFrame(pop,index=pd.Index([2001,2002,2003]))
```

**Comment by BigOrange128** [comment]
> 我在pandas0.22, python3.6下使用没有问题。这个应该是pandas新版本带来的问题，试一试下面的代码。
> 
> ```
> pd.DataFrame(pop,index=pd.Index([2001,2002,2003]))
> ```
这样可以正常使用，多谢！
